[package]
name = "portfolio"
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"
members = ["rs_lib"]

[lib]
crate-type = ["cdylib", "rlib"]
path = "rs_lib"

[profile.release]
codegen-units = 1
incremental = true
lto = true
opt-level = "z"
