# fly.toml app configuration file generated for thojensen on 2026-04-15T23:45:51+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'thojensen'
primary_region = 'arn'

[env]
  STATIC_DIR = "/app/static"
  DIST_DIR = "/app/frontend/dist"
  RENDERER_BIN = "/app/renderer"
  AXUM_ORIGIN = "http://127.0.0.1:8080"
  RUST_LOG = "INFO"


[metrics]
  port = 8080
  path = "/api/metrics"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "stop"
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
