# fly.toml app configuration file generated for thojensen on 2026-04-15T23:45:51+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'thojensen'
primary_region = 'arn'

[env]
  STATIC_DIR = "static"
  DIST_DIR = "frontend/dist"

[metrics]
  port = 8080
  path = "/api/metrics"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
