// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_locale_middleware from './routes/[locale]/_middleware.ts'
import * as $_locale_about_index from './routes/[locale]/about/index.tsx'
import * as $_locale_contact_index from './routes/[locale]/contact/index.tsx'
import * as $_locale_experience_index from './routes/[locale]/experience/index.tsx'
import * as $_locale_index from './routes/[locale]/index.tsx'
import * as $_locale_projects_bininspect_index from './routes/[locale]/projects/bininspect/index.tsx'
import * as $_locale_projects_index from './routes/[locale]/projects/index.tsx'
import * as $_locale_robots_txt from './routes/[locale]/robots.txt.ts'
import * as $_app from './routes/_app.tsx'
import * as $_error from './routes/_error.tsx'
import * as $_layout from './routes/_layout.tsx'
import * as $about from './routes/about.tsx'
import * as $api_bininspect_binary from './routes/api/bininspect/binary.ts'
import * as $api_bininspect_index from './routes/api/bininspect/index.ts'
import * as $api_bininspect_internal from './routes/api/bininspect/internal.ts'
import * as $api_bininspect_types from './routes/api/bininspect/types.ts'
import * as $api_bininspect_wasm from './routes/api/bininspect/wasm.ts'
import * as $api_assets_path_ from './routes/api/assets/[...path].ts'
import * as $api_github_repos from './routes/api/github/repos.ts'
import * as $api_images_image_ from './routes/api/images/[image].ts'
import * as $contact from './routes/contact.tsx'
import * as $experience from './routes/experience.tsx'
import * as $index from './routes/index.tsx'
import * as $projects from './routes/projects.tsx'
import * as $BinInspect from './islands/BinInspect.tsx'
import * as $ExperienceRepos from './islands/ExperienceRepos.tsx'
import * as $Header from './islands/Header.tsx'
import * as $HeaderMobileMenu from './islands/HeaderMobileMenu.tsx'
import * as $ThemeToggle from './islands/ThemeToggle.tsx'
const manifest = {
	routes: {
		'./routes/[locale]/_middleware.ts': $_locale_middleware,
		'./routes/[locale]/about/index.tsx': $_locale_about_index,
		'./routes/[locale]/contact/index.tsx': $_locale_contact_index,
		'./routes/[locale]/experience/index.tsx': $_locale_experience_index,
		'./routes/[locale]/index.tsx': $_locale_index,
		'./routes/[locale]/projects/bininspect/index.tsx':
			$_locale_projects_bininspect_index,
		'./routes/[locale]/projects/index.tsx': $_locale_projects_index,
		'./routes/[locale]/robots.txt.ts': $_locale_robots_txt,
		'./routes/_app.tsx': $_app,
		'./routes/_error.tsx': $_error,
		'./routes/_layout.tsx': $_layout,
		'./routes/about.tsx': $about,
		'./routes/api/bininspect/binary.ts': $api_bininspect_binary,
		'./routes/api/bininspect/index.ts': $api_bininspect_index,
		'./routes/api/bininspect/internal.ts': $api_bininspect_internal,
		'./routes/api/bininspect/types.ts': $api_bininspect_types,
		'./routes/api/bininspect/wasm.ts': $api_bininspect_wasm,
		'./routes/api/assets/[...path].ts': $api_assets_path_,
		'./routes/api/github/repos.ts': $api_github_repos,
		'./routes/api/images/[image].ts': $api_images_image_,
		'./routes/contact.tsx': $contact,
		'./routes/experience.tsx': $experience,
		'./routes/index.tsx': $index,
		'./routes/projects.tsx': $projects,
	},
	islands: {
		'./islands/BinInspect.tsx': $BinInspect,
		'./islands/ExperienceRepos.tsx': $ExperienceRepos,
		'./islands/Header.tsx': $Header,
		'./islands/HeaderMobileMenu.tsx': $HeaderMobileMenu,
		'./islands/ThemeToggle.tsx': $ThemeToggle,
	},
	baseUrl: import.meta.url,
}

export default manifest
