// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from './routes/_404.tsx'
import * as $_app from './routes/_app.tsx'
import * as $_layout from './routes/_layout.tsx'
import * as $index from './routes/index.tsx'
import * as $Entry from './islands/Entry.tsx'
import * as $ExternalLink from './islands/ExternalLink.tsx'
import * as $Header from './islands/Header.tsx'
import * as $NavItem from './islands/NavItem.tsx'
import * as $ProjectCard from './islands/ProjectCard.tsx'
import * as $ProjectCardExpander from './islands/ProjectCardExpander.tsx'
import * as $SmoothScrollButton from './islands/SmoothScrollButton.tsx'
import type { Manifest } from '$fresh/server.ts'

const manifest = {
	routes: {
		'./routes/_404.tsx': $_404,
		'./routes/_app.tsx': $_app,
		'./routes/_layout.tsx': $_layout,
		'./routes/index.tsx': $index,
	},
	islands: {
		'./islands/Entry.tsx': $Entry,
		'./islands/ExternalLink.tsx': $ExternalLink,
		'./islands/Header.tsx': $Header,
		'./islands/NavItem.tsx': $NavItem,
		'./islands/ProjectCard.tsx': $ProjectCard,
		'./islands/ProjectCardExpander.tsx': $ProjectCardExpander,
		'./islands/SmoothScrollButton.tsx': $SmoothScrollButton,
	},
	baseUrl: import.meta.url,
} satisfies Manifest

export default manifest
