lint:
    cargo clippy -- -D warnings

build:
    cargo build --release

dev:
    just --justfile ../frontend/justfile build
    RENDERER_BIN=../frontend/dist/renderer RUST_LOG=DEBUG cargo run .

clean:
    cargo clean
