lint:
    cargo clippy --locked --all-targets -- -D warnings

test:
    cargo test --locked

build:
    cargo build --release --locked

dev:
    RENDERER_BIN=../frontend/dist/renderer RUST_LOG=DEBUG cargo run

clean:
    cargo clean
