// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SocialButton } from "./SocialButton";

export type Buttons = { github: SocialButton, linkedin: SocialButton, resume: string, };
