// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExperienceItem = { name: string, description: string, url: string, stars: bigint, forks: bigint, language: string, language_color: string, type: string, downloads: bigint | null, pr_number?: bigint, pr_state?: string, additions?: bigint, deletions?: bigint, zed_extension_url?: string, github_url?: string, };
