// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpenGraph } from "./OpenGraph";
import type { StructuredData } from "./StructuredData";

/**
 * Per-route document head, defined on the Rust side and handed to the
 * renderer so every page gets its own title, canonical URL, and social
 * preview metadata.
 */
export type Head = { title: string, description: string, 
/**
 * Absolute production URL for this route; also used as `og:url`.
 */
canonical: string, robots: string, og: OpenGraph, structured_data: StructuredData, };
