/* eslint-disable */
// @ts-nocheck
/*    @@@@@@@@@@@@@ & ###############
   @@@@@@@@@@@@@@ &&& ###############
 @@@@@@@@@@@@@@ &&&&& ###############
############### &&&&& ###############
######## Generated by Qubit! ########
############### &&&&& ###############
############### &&&&& @@@@@@@@@@@@@@
############### && @@@@@@@@@@@@@@
############### & @@@@@@@@@@@@@    */

import type { Project } from "./Project.ts";
import type { Locale } from "./Locale.ts";
import type { LocaleData } from "./LocaleData.ts";
import type { About } from "./About.ts";
import type { ExperienceItem } from "./ExperienceItem.ts";
import type { Data } from "./Data.ts";
import type { Query } from "@qubit-rs/client";
import type { RenderOutput } from "./RenderOutput.ts";
import type { Assets } from "./Assets.ts";
import type { Head } from "./Head.ts";
import type { RenderInput } from "./RenderInput.ts";

export type { Project } from "./Project.ts";
export type { Locale } from "./Locale.ts";
export type { LocaleData } from "./LocaleData.ts";
export type { About } from "./About.ts";
export type { ExperienceItem } from "./ExperienceItem.ts";
export type { Data } from "./Data.ts";
export type { Query } from "@qubit-rs/client";
export type { RenderOutput } from "./RenderOutput.ts";
export type { Assets } from "./Assets.ts";
export type { Head } from "./Head.ts";
export type { RenderInput } from "./RenderInput.ts";

export type QubitServer = { data: Query<[], Data>, experience: Query<[], Array<ExperienceItem>>, render_input: Query<[input: RenderInput, ], RenderOutput> };