// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Buttons } from "./Buttons";
import type { Contact } from "./Contact";
import type { Experience } from "./Experience";
import type { Hero } from "./Hero";
import type { Meta } from "./Meta";
import type { Nav } from "./Nav";
import type { Theme } from "./Theme";
import type { Work } from "./Work";

export type LocaleData = { meta: Meta, nav: Nav, hero: Hero, buttons: Buttons, work: Work, experience: Experience, theme: Theme, contact: Contact, };
