// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Nav = { about: string, work: string, experience: string, contact: string, open_menu: string, close_menu: string, };
