// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpenGraphImage } from "./OpenGraphImage";

/**
 * Open Graph fields that are not already covered by title, description,
 * and canonical.
 */
export type OpenGraph = { type: string, site_name: string, locale: string, image: OpenGraphImage, };
