// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OpenGraphImage = { url: string, alt: string, mime: string, width: number, height: number, };
