// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Project = { slug: string, name: string, image_url: string, technologies: { [key in string]?: string }, description: string, overview: string, highlights: Array<string>, source_type: string, source_link: string, featured?: boolean, };
