// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Assets } from "./Assets";

export type RenderInput = {
  id: number;
  url: string;
  rpc_origin: string;
  assets: Assets;
};
