// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Assets } from "./Assets";
import type { Head } from "./Head";

export type RenderInput = { id: number, url: string, rpc_origin: string, assets: Assets, head: Head, };
