// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RenderOutput = { id: number, status: number, html: string | null, error: string | null, headers: { [key in string]?: string }, };
