// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which JSON-LD block, if any, the renderer should emit for a route.
 */
export type StructuredData = "none" | "person";
