// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Work = { subtitle: string, visit_project: string, download_app_store: string, };
