// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { About } from "./About";
import type { ExperienceItem } from "./ExperienceItem";
import type { LocaleData } from "./LocaleData";
import type { Project } from "./Project";

export type Data = { en: LocaleData, no: LocaleData, about: About, projects: Array<Project>, experience_items: Array<ExperienceItem>, };
