// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExperienceItem = {
  name: string;
  description: string;
  url: string;
  stars: number;
  forks: number;
  language: string;
  language_color: string;
  type: string;
  downloads: number | null;
  pr_number?: number | null;
  pr_state?: string | null;
  additions?: number | null;
  deletions?: number | null;
  zed_extension_url?: string | null;
  github_url?: string | null;
};
