// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import type { HeaderLocaleData } from "./HeaderLocaleData";

export type HeaderData = { en: HeaderLocaleData, no: HeaderLocaleData, };
