// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Buttons } from "./Buttons";
import type { Nav } from "./Nav";
import type { Theme } from "./Theme";

export type HeaderLocaleData = { nav: Nav, buttons: Buttons, theme: Theme, };
