// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Hero = { role: string, description: string, currently_building: string, explore_work: string, };
