// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hero } from "./Hero";
import type { Meta } from "./Meta";
import type { Nav } from "./Nav";

export type LocaleData = { meta: Meta, nav: Nav, hero: Hero, };
