// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A Last.fm track that is currently playing.
 */
export type NowPlayingTrack = { artist: string, name: string, image: string | null, album: string, url: string, };
