# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: CI & Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint-frontend:
    name: Frontend Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - run: bunx nx run init
      - run: bunx nx run frontend:lint

  lint-backend:
    name: Backend Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: backend
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - run: bunx nx run init
      - run: bunx nx run backend:lint

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    needs: [lint-frontend, lint-backend]
    if: github.event_name == 'push'
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
